on:
  push:
    branches:
      - master
    paths:
      - 'football-frontend/**'

name: Build FrontEnd

jobs:
  deploy:
    name: Build, Test 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Build Front-End
      id: build-frontend
      working-directory: football-frontend
      env: 
        REACT_APP_SERVER_HTTP: https
        REACT_APP_SERVER_HOST: football.mantoni.me
        REACT_APP_SERVER_HTTP_PORT: 443
        REACT_APP_SERVER_WS_PORT: 443
        REACT_APP_SERVER_PATH_PREFIX: api/
      run: |
        npm ci
        npm run build
        CI=true npm test
