on:
  push:
    branches:
      - master
    paths:
      - 'football-frontend/**'

name: Build and Deploy FrontEnd

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Build Front-End
      id: build-frontend
      working-directory: football-frontend
      env: 
        REACT_APP_SERVER_HTTP: https
        REACT_APP_SERVER_HOST: football.mantoni.me
        REACT_APP_SERVER_HTTP_PORT: 443
        REACT_APP_SERVER_WS_PORT: 443
        REACT_APP_SERVER_PATH_PREFIX: api/
      run: |
        npm ci
        npm run build
        
    - name: Deploy Front-End
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: www.football.mantoni.me
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: './football-frontend/build'
